class OptimizeMysqlTables < ActiveRecord::Migration
  def self.up
		add_index(:attachments, %w(published deleted archived), :name => 'pub_del_archived')
		add_index(:categories, %w(category_type_id id), :name => 'id_category')
		add_index(:categories, %w(parent_id name), :name => 'parent_name')
		add_index(:connectors, %w(page_id page_version), :name => 'page_version')
		add_index(:connectors, %w(page_id page_version container position), :name => 'page_version_position_container')
		add_index(:connectors, %w(connectable_id connectable_type connectable_version), :name => 'connector_type_version')
		add_index(:content_types , %w(content_type_group_id id), :name => 'group_and_id')
		add_index(:group_permissions, %w(id group_id), :name => 'id_and_group')
		add_index(:group_permissions, %w(group_id), :name => 'group')
		add_index(:group_permissions, %w(permission_id), :name => 'permission')
		add_index(:group_sections, %w(section_id), :name => 'section')
		add_index(:group_sections, %w(section_id group_id), :name => 'section_and_group')
		add_index(:group_sections, %w(group_id), :name => 'group')
		add_index(:group_type_permissions, %w(group_type_id permission_id), :name => 'group_and_permission')
		add_index(:groups, %w(group_type_id), :name => 'group')
		add_index(:groups, %w(code), :name => 'code')
		add_index(:groups, %w(id code), :name => 'id_and_code')
		add_index(:html_block_versions, %w(html_block_id published deleted), :name => 'block_published_deleted')
		add_index(:html_block_versions, %w(version html_block_id), :name => 'version_and_block')
		add_index(:html_blocks, %w(id version), :name => 'id_and_version')
		add_index(:html_blocks, %w(id published deleted), :name => 'id_published_deleted')
		add_index(:page_versions, %w(id page_id deleted), :name => 'id_page_deleted')
		add_index(:pages, %w(id deleted), :name => 'id_deleted')
		add_index(:pages, %w(published deleted archived path), :name => 'pub_del_arch_path')
		add_index(:pages, %w(deleted path), :name => 'del_path')
		add_index(:permissions, %w(name), :name => 'name')
		add_index(:redirects, %w(from_path id), :name => 'id_from_path')
		add_index(:section_nodes, %w(id section_id), :name => 'id_section')
		add_index(:section_nodes, %w(id node_type position), :name => 'id_type_position')
		add_index(:user_group_memberships, %w(user_id), :name => 'user')
		add_index(:user_group_memberships, %w(group_id user_id), :name => 'group_and_user')
  end

  def self.down
		remove_index(:attachments, :name => 'pub_del_archived')
		remove_index(:categories, :name => 'id_category')
		remove_index(:categories, :name => 'parent_name')
		remove_index(:connectors, :name => 'page_version')
		remove_index(:connectors, :name => 'page_version_position_container')
		remove_index(:connectors, :name => 'connector_type_version')
		remove_index(:content_types , :name => 'group_and_id')
		remove_index(:group_permissions, :name => 'id_and_group')
		remove_index(:group_permissions, :name => 'group')
		remove_index(:group_permissions, :name => 'permission')
		remove_index(:group_sections, :name => 'section')
		remove_index(:group_sections, :name => 'section_and_group')
		remove_index(:group_sections, :name => 'group')
		remove_index(:group_type_permissions, :name => 'group_and_permission')
		remove_index(:groups, :name => 'group')
		remove_index(:groups, :name => 'code')
		remove_index(:groups, :name => 'id_and_code')
		remove_index(:html_block_versions, :name => 'block_published_deleted')
		remove_index(:html_block_versions, :name => 'version_and_block')
		remove_index(:html_blocks, :name => 'id_and_version')
		remove_index(:html_blocks, :name => 'id_published_deleted')
		remove_index(:page_versions, :name => 'id_page_deleted')
		remove_index(:pages, :name => 'id_deleted')
		remove_index(:pages, :name => 'pub_del_arch_path')
		remove_index(:pages, :name => 'del_path')
		remove_index(:permissions, :name => 'name')
		remove_index(:redirects, :name => 'id_from_path')
		remove_index(:section_nodes, :name => 'id_section')
		remove_index(:section_nodes, :name => 'id_type_position')
		remove_index(:user_group_memberships, :name => 'user')
		remove_index(:user_group_memberships, :name => 'group_and_user')
  end
end
